apiVersion: apps/v1
kind: Deployment

metadata:
  name: atmo-deployment
  namespace: suborbital
  labels:
    app: atmo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: atmo

  template:
    metadata:
      labels:
        app: atmo

    spec:
      containers:
        - name: atmo
          image: suborbital/atmo:wait
          command: ["atmo"]
          # if you are using your own image with a bundle baked in,
          # you do not need the --wait flag, though it won't do any harm
          args: ["--wait"]

          ports:
            - containerPort: 8080
            - containerPort: 443

          env:
            # uncomment and set your domain name to use LetsEncrypt
            # - name: ATMO_DOMAIN
            #   value: "example.com"
            
            - name: ATMO_HTTP_PORT
              # this should (almost) always be set to 8080
              # as port 80 is intentionally not available
              value: "8080"
            
            - name: ATMO_LOG_LEVEL
              # set the log level to 'debug' to see more detailed logs
              value: "info"

          volumeMounts:
            - name: bundle-storage
              mountPath: /home/atmo

      volumes:
        - name: bundle-storage
          persistentVolumeClaim:
            # ensure you apply one of the atmo-*-pvc.yml manifests in this 
            # directory to match the k8s environment you're using (K3s, GCP, EKS, etc.)
            claimName: atmo-bundle-pvc
